image: registry.gitlab.com/maketechnology/equo/docker/gradle5.4.1:adoptopenjdk8-alpine

stages:
  - build
  - test
  - report
  - release

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle-home
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn-cache
  gradle_opt: "--build-cache --no-daemon"

# HOME is to cwd so bnd will download to ~/.bnd and ~/.m2 with ~=HOME
cache:
  key: "gradle"
  paths:
    - .yarn-cache/
    - .gradle-home/
    - .m2/
    - .bnd/

.global_before_scripts: &global_before_scripts
  - export HOME=$CI_PROJECT_DIR
  - printf "%b\n" "$REGISTRY_CREDENTIALS" | base64 -d > $HOME/.npmrc

before_script:
  - *global_before_scripts

.all:
  artifacts:
    reports:
       junit:
          - "*/generated/test-reports/test/TEST-*.xml"
          - "*/generated/test-reports/testOSGi/TEST-*.xml"
    paths:
      - cnf/release
      - cnf/cache
      - cnf/build
      - build
      - build-cache
      - com.make.equo*/generated/*.jar
      - com.make.equo*/generated/jacoco/test.exec
    expire_in: 12w

.print_converage: &print_converage
- awk -F, '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv

build:
  extends: .all
  stage: build
  script:
    - gradle $gradle_opt assemble

test:
  extends: .all
  stage: test
  script:
    - gradle $gradle_opt test

test.integration:
  extends: .all
  image: registry.gitlab.com/maketechpub/docker/adopt:ubuntu.jdk8.gtk3
  stage: test
  before_script:
    - *global_before_scripts
    - Xvfb :1 -screen 0 1152x720x24+32 -ac -noreset 2> xvfb.err &
    - export DISPLAY=:1
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get install -y nodejs    
  script:
    - ./gradlew $gradle_opt testOSGi

coverage.report:
  extends: .all
  stage: report
  script:
    - gradle $gradle_opt jacocoRootReport
    - *print_converage
  except:
    - master

full.coverage.report:
  extends: .all
  stage: report
  script:
    - gradle $gradle_opt jacocoRootReport -PreportHtml=true
    - *print_converage
  only:
    - master

release:
  extends: .all
  stage: release
  script:
    - gradle $gradle_opt release
    - gradle $gradle_opt publish
    - gradle $gradle_opt run.p2
    - gradle $gradle_opt run.p2category
    - gradle $gradle_opt publishP2
    - gradle com.make.equo.monaco:yarnPublish --rerun-tasks
  only:
    - master

pages:
  stage: release
  script:
    - cp -R $CI_PROJECT_DIR/build/reports/jacoco/jacocoRootReport/html/ public/
    - ls -R public/
  artifacts:
    paths:
    - public
  only:
    - master